version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000  # Pass the UID from your local system
        GID: 1000 # Pass the GID from your local system
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    depends_on:
      - db
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    
  db:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
